apiVersion: v1
kind: Namespace
metadata:
  name: elk
---
apiVersion: v1
kind: Namespace
metadata:
  name: wazuh
---
apiVersion: v1
kind: Namespace
metadata:
  name: elasticflow
---
apiVersion: v1
kind: Namespace
metadata:
  name: mgmt
