server.name: "rsd-kibana"
server.host: "0.0.0.0"
server.ssl.enabled: true
server.ssl.certificate: /opt/rsd/config/certs/kbn/kbn.crt
server.ssl.key: /opt/rsd/config/certs/kbn/kbn.key

elasticsearch.hosts: ["https://els-nd01:9200"]
elasticsearch.username: "kibana_system"
elasticsearch.password: "${KIBANA_PASSWORD}"
elasticsearch.ssl.certificateAuthorities: [ "/opt/rsd/config/certs/ca/ca.crt" ]
elasticsearch.ssl.verificationMode: certificate

monitoring.ui.container.elasticsearch.enabled: true
