apiVersion: apps/v1
kind: Deployment
metadata:
  name: lgs-pl
  namespace: elk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: rdenck/lgs:v1.0.0
        ports:
        - containerPort: 5044
        - containerPort: 9600
        volumeMounts:
        - name: config
          mountPath: /opt/rsd/pipeline/logstash.conf
          subPath: logstash.conf
      volumes:
      - name: config
        configMap:
          name: lgs-config
