cluster.name: "rsd-cluster"
network.host: 0.0.0.0
path.data: /opt/rsd/data
path.logs: /opt/rsd/logs

# Seguran√ßa TLS (Zero Trust)
xpack.security.enabled: true
xpack.security.http.ssl:
  enabled: true
  key: certs/els/els.key
  certificate: certs/els/els.crt
  certificate_authorities: certs/ca/ca.crt

xpack.security.transport.ssl:
  enabled: true
  verification_mode: certificate
  key: certs/els/els.key
  certificate: certs/els/els.crt
  certificate_authorities: certs/ca/ca.crt

# Cluster Settings
discovery.seed_hosts: ["els-nd01", "els-nd02", "els-nd03"]
cluster.initial_master_nodes: ["els-nd01", "els-nd02", "els-nd03"]
bootstrap.memory_lock: true
