apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rsd-ingress
  namespace: mgmt
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  tls:
  - hosts:
    - kibana.rsd.local
    - flow.rsd.local
    secretName: rsd-tls-secret
  rules:
  - host: kibana.rsd.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kbn-ui
            port:
              number: 5601
  - host: flow.rsd.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: efw-kbn
            port:
              number: 5601
