# Elastiflow Unified Collector Configuration
elastiflow:
  collector:
    name: rsd-efw-01
  elasticsearch:
    hosts: ["https://els-nd01:9200"]
    username: elastic
    password: "${ELASTIC_PASSWORD}"
    ssl:
      enabled: true
      ca: /opt/rsd/config/certs/ca/ca.crt
      verify: true
